version: '3'

services:
  app:
    image: acrek.azurecr.io/partsunlimitedwebsite:latest
    ports:
      - "8080:80"
    networks:
      - default

 networks:
      default:
          external:
          name: nat