{{- if .Values.ingress.enabled -}}
{{- $fullName := include "PartsUnlimited.API.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "PartsUnlimited.API.name" . }}
    chart: {{ template "PartsUnlimited.API.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    system: {{ $.Values.system.name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    traefik.ingress.kubernetes.io/service-weights: |
      {{- range $canary := .Values.canaries }}
        {{ $fullName }}-{{ .name }}: {{ .weight }}%
      {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      {{- range $canary := $.Values.canaries }}
      - path: {{ $ingressPath }}
        backend:
          serviceName: {{ $fullName }}-{{ .name }}
          servicePort: http
      {{- end }}
  {{- end }}

{{- end }}